services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: portfolio_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    restart: unless-stopped
    ports:
      - "8087:80"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: portfolio_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: https://portfolio.devifyo.cloud/dbase/
    ports:
      - "8088:80"
    depends_on:
      - db
